### ISSUE TITLE
Add documentation regarding chart file creation

### ISSUE THREAD

**Issue by creeper-0910** [neogeek/rhythm-game-utilities#89]
I tried to create a .chart file but could not find any tools or documentation to create a .chart file.
If you have any tools or other information regarding the creation of a .chart file, I would appreciate it if you could add the URL or other information!
Also, if possible, it would be great if you could support NoteEditor or other formats.

Thank you for a very nice project!
(I apologize if some parts are difficult to understand due to the use of translations.)

**Comment by neogeek** [comment]
I've been using the application Moonscraper for charting songs and it's worked out really well. I can add it to the documentation so that its easier to find/reference.

https://github.com/FireFox2000000/Moonscraper-Chart-Editor

NoteEditor looks really cool! I'll add it to a list of potential features. For now I'm going to try and keep the feature set minimal until we hit a stable release.

**Comment by creeper-0910** [comment]
Thank you very much!
I sincerely wish you success and development of this project!

**Comment by neogeek** [comment]
Thank you! And let me know if you have any further questions.
